security:
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        our_users:
            entity: { class: AppBundle\Entity\User, property: login }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            logout:
                path: /logout
                target: /
